Get-AppxPackage Microsoft.VCLibs.140.00 | Remove-AppxPackage
Get-AppxPackage Microsoft.NET.Native.Framework.1.0 | Remove-AppxPackage
Get-AppxPackage Microsoft.NET.Native.Runtime.1.0 | Remove-AppxPackage
Get-AppxPackage Microsoft.Windows.CloudExperienceHost | Remove-AppxPackage
Get-AppxPackage Microsoft.AAD.BrokerPlugin | Remove-AppxPackage
Get-AppxPackage Microsoft.AccountsControl | Remove-AppxPackage
Get-AppxPackage Microsoft.BioEnrollment | Remove-AppxPackage
Get-AppxPackage Microsoft.LockApp | Remove-AppxPackage
Get-AppxPackage Microsoft.MicrosoftEdge | Remove-AppxPackage
Get-AppxPackage Microsoft.Windows.AssignedAccessLockApp | Remove-AppxPackage
Get-AppxPackage Microsoft.Windows.ContentDeliveryManager | Remove-AppxPackage
Get-AppxPackage Microsoft.Windows.Cortana | Remove-AppxPackage
Get-AppxPackage Microsoft.Windows.ParentalControls | Remove-AppxPackage
Get-AppxPackage Microsoft.Windows.ShellExperienceHost | Remove-AppxPackage
Get-AppxPackage Microsoft.WindowsFeedback | Remove-AppxPackage
Get-AppxPackage Microsoft.XboxGameCallableUI | Remove-AppxPackage
Get-AppxPackage Microsoft.XboxIdentityProvider | Remove-AppxPackage
Get-AppxPackage Windows.ContactSupport | Remove-AppxPackage
Get-AppxPackage Windows.immersivecontrolpanel | Remove-AppxPackage
Get-AppxPackage Windows.MiracastView | Remove-AppxPackage
Get-AppxPackage Windows.PrintDialog | Remove-AppxPackage
Get-AppxPackage Windows.PurchaseDialog | Remove-AppxPackage
Get-AppxPackage Microsoft.windowscommunicationsapps | Remove-AppxPackage
Get-AppxPackage Microsoft.Getstarted | Remove-AppxPackage
Get-AppxPackage Microsoft.Windows.Photos | Remove-AppxPackage
Get-AppxPackage Microsoft.WindowsCamera | Remove-AppxPackage
Get-AppxPackage Microsoft.WindowsStore | Remove-AppxPackage
Get-AppxPackage Microsoft.XboxApp | Remove-AppxPackage
Get-AppxPackage Microsoft.BingWeather | Remove-AppxPackage
Get-AppxPackage Windows.devicesflow | Remove-AppxPackage
Get-AppxPackage Microsoft.WindowsAlarms | Remove-AppxPackage
Get-AppxPackage Microsoft.ZuneVideo | Remove-AppxPackage
Get-AppxPackage Microsoft.ZuneMusic | Remove-AppxPackage
Get-AppxPackage Microsoft.WindowsSoundRecorder | Remove-AppxPackage
Get-AppxPackage Microsoft.WindowsMaps | Remove-AppxPackage
Get-AppxPackage Microsoft.WindowsCalculator | Remove-AppxPackage
Get-AppxPackage Microsoft.People | Remove-AppxPackage
Get-AppxPackage Microsoft.Office.OneNote | Remove-AppxPackage
Get-AppxPackage Microsoft.Appconnector | Remove-AppxPackage
Get-AppxPackage Microsoft.3DBuilder | Remove-AppxPackage
